bugtracker/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users , :skip => [:sessions]
  as :user do
    get 'sign-in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign-in' => 'devise/sessions#create', :as => :user_session
    get 'sign-out' => 'devise/sessions#destroy', :as => :destroy_user_session

  end

  resources :tickets do
    resource :comments
  end
  resources :statuses
  resources :users do
    root 'welcome#index'

  end

  resources :clients

end

bugtracker/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :status
  belongs_to :client
  belongs_to :user
  has_many :comments
end

bugtracker/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:new, :create]
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new

  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @send = Ticket.new(params[:email])

    respond_to do |format|
      if @ticket.save
        ClientMailer.send_email(@send).deliver

        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:status_id, :email, :problem)
    end
end

bugtracker/app/helpers/tickets_helper.rb
module TicketsHelper
end

bugtracker/app/views/tickets/_form.html.haml
%header#header
  %nav.navbar.navbar-default.navbar-static-top{:role => "banner"}
    .container
      .navbar-collapse.collapse
        .menu
          %ul.nav.nav-tabs{:role => "tablist"}
            %li{:role => "presentation"}
            %a= link_to 'Log-out', destroy_user_session_path

= form_for(@ticket) do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2
        = pluralize(@ticket.errors.count, "error")
        prohibited this ticket from being saved:
      %ul
        - @ticket.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :status
    %br/
    = f.select :status_id, options_for_select(Status.all.collect {|s| [s.status, s.id] }), |
      :include_blank => false
  .field
    = f.label :user
    %br/
    = f.select :user, options_for_select(User.all.collect {|u| [u.email] }), |
      :include_blank => false
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :problem
    %br/
    = f.text_area :problem
  .actions
    = f.submit

bugtracker/app/views/tickets/edit.html.haml
%h1 Editing ticket
= render 'form'
= link_to 'Show', @ticket
|
\#{link_to 'Back', tickets_path}

bugtracker/app/views/tickets/index.html.haml
%h1 Listing Tickets
%header#header
  %nav.navbar.navbar-default.navbar-static-top{:role => "banner"}
    .container
      .navbar-collapse.collapse
        .menu
          %ul.nav.nav-tabs{:role => "tablist"}
            %li{:role => "presentation"}
            %a= link_to 'Home', root_path
            %li{:role => "presentation"}
            %a= link_to 'Add status', new_status_path
            %li{:role => "presentation"}
            %a= link_to 'Add user', new_user_path
            %li{:role => "presentation"}
            %a= link_to 'Log-out', destroy_user_session_path
        / /.container
      / /nav
      / /header
  %table
    %thead
      %tr
        %th Id tickets
        %th Status
        %th User
        %th Client email
        %th Problem
        %th{:colspan => "3"}
    %tbody
      - @tickets.each do |ticket|
        %tr
          %th= 'ABC-%s' % ticket.id
          %td= ticket.status_id.nil? ? 'New unassigned tickets' : ticket.status.status
          %td= ticket.user_id.nil? ? 'unassigned' : ticket.user.login
          %td= ticket.email
          %td= ticket.problem
          %td= link_to 'Show', ticket
          %td= link_to 'Edit', edit_ticket_path(ticket)
          %td= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Ticket', new_ticket_path

bugtracker/app/views/tickets/new.html.haml
%h1 New ticket
= render 'form'
= link_to 'Back', tickets_path

bugtracker/app/views/tickets/show.html.haml
%p#notice= notice
%p
  %strong Status:
  = @ticket.status_id
%p
  %strong User:
  = @ticket.user_id
%p
  %strong Client:
  = @ticket.email
%p
  %strong Problem:
  = @ticket.problem
%p
  %strong Title:
  = @ticket.status
%p
  %strong Text:
  = @ticket.problem
%h2 Comments
- @ticket.comments.each do |comment|
  %p
    %strong Commenter:
    = comment.commenter
  %p
    %strong Comment:
    = comment.body
%h2 Add a comment:
= form_for([@ticket, @ticket.comments.build]) do |f|
  %p
    = f.label :commenter
    %br/
    = f.text_field :commenter
  %p
    = f.label :body
    %br/
    = f.text_area :body
  %p
    = f.submit
= link_to 'Edit', edit_ticket_path(@ticket)
|
\#{link_to 'Back', tickets_path}